spring:
  application:
    name: trafficController

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:traffic
    driver-class-name: org.h2.Driver
    username: sa
    password: mohan

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
